name: build-android

on:
  push:
    branches: [ "acicd-test" ]
  pull_request:

jobs:
  build-android:

    timeout-minutes: 5
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        config:
          - {api_level: 23, ndk_version: 24.0.8215888, abi: arm64-v8a}

    steps:
    - name: Install dependencies
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt install -y git build-essential cmake unzip openjdk-17-jdk
        sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
        ANDROID_TOOLS_PATH=${HOME}/sdk-sources/android-tools.zip
        mkdir -p ${HOME}/sdk-sources
        ANDROID_TOOLS_URL=https://googledownloads.cn/android/repository/commandlinetools-linux-11076708_latest.zip
        curl --location --fail "${ANDROID_TOOLS_URL}" -o "$ANDROID_TOOLS_PATH"
        ANDROID_HOME="${HOME}/SDKs/android"
        mkdir -p "$ANDROID_HOME"
        unzip -o "$ANDROID_TOOLS_PATH" -d "$ANDROID_HOME"
        ANDROID_BUILD_TOOLS_VERSION=28.0.3
        ANDROID_API_LEVEL=${{ matrix.config.api_level }}
        ANDROID_NDK_VERSION=${{ matrix.config.ndk_version }}
        JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
        yes | "${ANDROID_HOME}"/cmdline-tools/bin/sdkmanager --sdk_root="${ANDROID_HOME}" --install "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" "platform-tools" "platforms;android-${ANDROID_API_LEVEL}" "ndk;${ANDROID_NDK_VERSION}"
        ls -l "${ANDROID_HOME}"

    - name: build libs
      run: |
        ANDROID_API_LEVEL=${{ matrix.config.api_level }}
        ANDROID_NDK_VERSION=${{ matrix.config.ndk_version }}
        ANDROID_ABI=${{ matrix.config.abi }}
        curl -sL https://codeload.github.com/bitbi-core/pow/zip/refs/tags/v0.2.2 -o pow.zip
        POW_HOME=$HOME/pow
        mkdir -p $POW_HOME
        unzip pow.zip -d $POW_HOME
        cd $POW_HOME/pow-0.2.2
        mkdir build
        cd build
        export ANDROID_NDK_HOME="${HOME}/SDKs/android/ndk/${ANDROID_NDK_VERSION}"
        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake  -DANDROID_ABI=$ANDROID_ABI -DANDROID_PLATFORM=android-$ANDROID_API_LEVEL ..
        make -j$(nproc)
        ls $POW_HOME/pow-0.2.2/build

        echo "-----------------building curl-----------------"
        curl -sL https://curl.se/download/curl-8.8.0.tar.gz -o curl-8.8.0.tar.gz
        tar -xvf curl-8.8.0.tar.gz
        CURL_HOME=$HOME/curl
        mv curl-8.8.0 $CURL_HOME
        cd $CURL_HOME
        mkdir build
        cd build
        echo "pwd: $(pwd)"
        echo "ANDROID_NDK_HOME: $ANDROID_NDK_HOME"
        ls $ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake
        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_NDK=$ANDROID_NDK_HOME -DANDROID_ABI=$ANDROID_ABI -DANDROID_PLATFORM=android-$ANDROID_API_LEVEL -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DCURL_ENABLE_SSL=OFF ..
        make -j$(nproc) 
        

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build Miner
      run: |
        export CROSS_COMPILE_FOR_NDK=yes
        ./autogen.sh
        POW_HOME=$HOME/pow/pow-0.2.2
        CURL_HOME=$HOME/curl
        ./configure CPPFLAGS=" -I$POW_HOME/src -I$CURL_HOME/include" LIBS="-L$POW_HOME/build -lrandomx -lz -L$CURL_HOME/build/lib -lcurl" --host=arm64-linux-androideab --disable-assembly
        make -j$(nproc)
