name: build-windows

on:
  push:
    branches: [ "wcicd-test" ]
  pull_request:

jobs:
    build-windows-msys2:

        timeout-minutes: 15
        runs-on: windows-latest
    
        strategy:
          matrix:
            config:
              - {c: "gcc", cxx: "g++"}
              # - {c: "clang", cxx: "clang++"}
    
        defaults:
          run:
            shell: msys2 {0}
    
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            submodules: recursive
    
        - name: Setup MSYS2
          uses: eine/setup-msys2@v2
          with:
            update: true
            install: mingw-w64-x86_64-toolchain mingw-w64-x86_64-clang mingw-w64-x86_64-lld mingw-w64-x86_64-cmake make
    
        - name: Build Miner
          run: |
            ./autogen.sh
            ./configure CPPFLAGS=" -I/path-to-pow/src" LIBS="-L/path-to-pow/build -lrandomx"
            make

        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: windows-msys2-${{ matrix.config.c }}
            path: ./minerd